from supabase import create_client


db = create_client('https://lkolxrovwsrrdltbhcvw.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrb2x4cm92d3NycmRsdGJoY3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTIwNjAsImV4cCI6MjA3MTE4ODA2MH0.uTjpEIHK-U_9pxRK5DF7AFHCZH0soRZmaurlwXuMs7k')
